name: Run Gradle test

on:
  push:
    branches:
      - main
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      name: setup gradle
    - name: Execute Gradle build
      run: ./gradlew build